/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package FinalProjectFall2022ASE;

import simView.*;

import java.awt.*;
import java.io.*;

import FinalProjectFall2022ASE.GeneralWard.GWBed1;
import FinalProjectFall2022ASE.SemiSepcialWard.SSWBed1;
import FinalProjectFall2022ASE.SpecialWard.SWBed1;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class HospitalSystem extends ViewableDigraph{


public HospitalSystem(){
    this("Hospital System");
}

public HospitalSystem(String nm){
    super(nm);
    hospitalSystemConstruct();
}

public void hospitalSystemConstruct(){

    this.addOutport("hospitalExit");

    ViewableAtomic patientGenr = new PatientGenerator("patientGenr",15);
    ViewableAtomic patientQueue = new PatientQueue("patientQueue");
    
    
    
    ViewableAtomic gwBed1 = new GWBed1("GWBed1");
    ViewableAtomic gwBed2 = new GWBed1("GWBed2");
    
    ViewableAtomic sswBed1 = new SSWBed1("SSWBed1");
    ViewableAtomic sswBed2 = new SSWBed1("SSWBed2");
    
    ViewableAtomic swBed1 = new SWBed1("SWBed1");
    ViewableAtomic swBed2 = new SWBed1("SWBed2");
   
	add(patientGenr);
	add(patientQueue);
	
	add(gwBed1);
	add(gwBed2);
	
	add(sswBed1);
	add(sswBed2);
	
	add(swBed1);
	add(swBed2);
	
	// patient genr to patientQueue
	addCoupling(patientGenr,"patientIncomingHospital",patientQueue,"patientIn");
	
	// pq to GW
	addCoupling(patientQueue,"pqGWBed1",gwBed1,"gwBed1In");
	addCoupling(patientQueue,"pqGWBed2",gwBed2,"gwBed2In");
	
	// pq to SSW
	addCoupling(patientQueue,"pqSSWBed1",sswBed1,"sswBed1In");
	addCoupling(patientQueue,"pqSSWBed2",sswBed2,"sswBed2In");
	
	// pq to SW
	addCoupling(patientQueue,"pqSWBed1",swBed1,"swBed1In");
	addCoupling(patientQueue,"pqSWBed2",swBed2,"swBed12In");
	
	// GW to out
	addCoupling(patientQueue,"gwBed1Out",this,"hospitalExit");
	addCoupling(patientQueue,"gwBed2Out",this,"hospitalExit");
	
	// SSW to out
	addCoupling(patientQueue,"sswBed1Out",this,"hospitalExit");
	addCoupling(patientQueue,"sswBed2Out",this,"hospitalExit");
	
	// SW to out
	addCoupling(patientQueue,"swBed1Out",this,"hospitalExit");
	addCoupling(patientQueue,"swBed2Out",this,"hospitalExit");
}


   
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(625, 341);
        if((ViewableComponent)withName("GWBed2")!=null)
             ((ViewableComponent)withName("GWBed2")).setPreferredLocation(new Point(273, 87));
        if((ViewableComponent)withName("SSWBed2")!=null)
             ((ViewableComponent)withName("SSWBed2")).setPreferredLocation(new Point(240, 192));
        if((ViewableComponent)withName("patientGenr")!=null)
             ((ViewableComponent)withName("patientGenr")).setPreferredLocation(new Point(20, 143));
        if((ViewableComponent)withName("GWBed1")!=null)
             ((ViewableComponent)withName("GWBed1")).setPreferredLocation(new Point(237, 262));
        if((ViewableComponent)withName("SWBed2")!=null)
             ((ViewableComponent)withName("SWBed2")).setPreferredLocation(new Point(50, 50));
        if((ViewableComponent)withName("patientQueue")!=null)
             ((ViewableComponent)withName("patientQueue")).setPreferredLocation(new Point(116, 183));
        if((ViewableComponent)withName("SWBed1")!=null)
             ((ViewableComponent)withName("SWBed1")).setPreferredLocation(new Point(50, 50));
        if((ViewableComponent)withName("SSWBed1")!=null)
             ((ViewableComponent)withName("SSWBed1")).setPreferredLocation(new Point(50, 50));
    }
}
