/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package FinalProjectFall2022ASE;

import simView.*;

import java.awt.*;
import java.io.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class HospitalSystem extends ViewableDigraph{


public HospitalSystem(){
    this("Hospital System");
}

public HospitalSystem(String nm){
    super(nm);
    hospitalSystemConstruct();
}

public void hospitalSystemConstruct(){

    this.addOutport("out");

    ViewableAtomic patientGenr = new PatientGenerator("patientGenr",12);
    ViewableAtomic patientQueue = new PatientQueue("patientQueue");
    ViewableAtomic generalWardQueue = new GeneralWardQueue("generalWardQueue");
    ViewableAtomic semiSpecialWardQueue = new SemiSpecialWardQueue("semiSpecialWardQueue");
    ViewableAtomic specialWardQueue = new SpecialWardQueue("specialWardQueue");

     add(patientGenr);
     add(patientQueue);
     add(generalWardQueue);
     add(semiSpecialWardQueue);
     add(specialWardQueue);

     addCoupling(patientGenr,"out",patientQueue,"patientIn");
     addCoupling(patientQueue,"outGeneralWard",generalWardQueue,"generalWardIn");
     addCoupling(patientQueue,"outSemiSpecialWard",semiSpecialWardQueue,"semiSpecialWardIn");
     addCoupling(patientQueue,"outSpecialWard",specialWardQueue,"specialWardIn");
     addCoupling(generalWardQueue,"dischargeFromGeneralWard",this,"out");
     addCoupling(semiSpecialWardQueue,"dischargeFromSemiSpecialWard",this,"out");
     addCoupling(specialWardQueue,"dischargeFromSpecialWard",this,"out");

}


   
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(991, 517);
        if((ViewableComponent)withName("patientQueue")!=null)
             ((ViewableComponent)withName("patientQueue")).setPreferredLocation(new Point(178, 202));
        if((ViewableComponent)withName("specialWardQueue")!=null)
             ((ViewableComponent)withName("specialWardQueue")).setPreferredLocation(new Point(522, 64));
        if((ViewableComponent)withName("patientGenr")!=null)
             ((ViewableComponent)withName("patientGenr")).setPreferredLocation(new Point(12, 246));
        if((ViewableComponent)withName("generalWardQueue")!=null)
             ((ViewableComponent)withName("generalWardQueue")).setPreferredLocation(new Point(513, 424));
        if((ViewableComponent)withName("semiSpecialWardQueue")!=null)
             ((ViewableComponent)withName("semiSpecialWardQueue")).setPreferredLocation(new Point(502, 235));
    }
}
